COLS = [
    "TIPO_REG", "DATA", "CODBDI", "TICKER", "TPMERC", "NOMRES", "ESPECI",
    "PRAZOT", "MOEDA",
    "ABERTURA", "MAXIMO", "MINIMO", "MEDIO", "FECHAMENTO",
    "OFER_COMPRA", "OFER_VENDA",
    "NEGOCIOS", "QUANT_TIT", "VOL_TOTAL",
    "PRE_EXERC", "INDOPC", "DATVEN", "FATCOT", "PTOEXE", "CODISI", "DISMES"
]